package accesodato;
// Generated 21-jun-2014 16:32:35 by Hibernate Tools 3.2.1.GA



/**
 * Detallecompra generated by hbm2java
 */
public class Detallecompra  implements java.io.Serializable {


     private Integer id;
     private Compra compra;
     private Producto producto;
     private float preciounidad;
     private int cantidad;

    public Detallecompra() {
    }

    public Detallecompra(Compra compra, Producto producto, float preciounidad, int cantidad) {
       this.compra = compra;
       this.producto = producto;
       this.preciounidad = preciounidad;
       this.cantidad = cantidad;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Compra getCompra() {
        return this.compra;
    }
    
    public void setCompra(Compra compra) {
        this.compra = compra;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public float getPreciounidad() {
        return this.preciounidad;
    }
    
    public void setPreciounidad(float preciounidad) {
        this.preciounidad = preciounidad;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }




}


