package accesodato;
// Generated 21-jun-2014 16:32:35 by Hibernate Tools 3.2.1.GA



/**
 * Detalleventa generated by hbm2java
 */
public class Detalleventa  implements java.io.Serializable {


     private Integer id;
     private Venta venta;
     private Producto producto;
     private float preciounidad;
     private int cantidad;

    public Detalleventa() {
    }

    public Detalleventa(Venta venta, Producto producto, float preciounidad, int cantidad) {
       this.venta = venta;
       this.producto = producto;
       this.preciounidad = preciounidad;
       this.cantidad = cantidad;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Venta getVenta() {
        return this.venta;
    }
    
    public void setVenta(Venta venta) {
        this.venta = venta;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public float getPreciounidad() {
        return this.preciounidad;
    }
    
    public void setPreciounidad(float preciounidad) {
        this.preciounidad = preciounidad;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }




}


